# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-23 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('trigger_pin', models.IntegerField()),
                ('echo_pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('pin', models.IntegerField()),
                ('is_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RaspberryPi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('address', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RGBLight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('pinRed', models.IntegerField()),
                ('pinGreen', models.IntegerField()),
                ('pinBlue', models.IntegerField()),
                ('is_on', models.BooleanField(default=False)),
                ('colorRed', models.IntegerField()),
                ('colorGreen', models.IntegerField()),
                ('colorBlue', models.IntegerField()),
                ('pi', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='smartpihome.RaspberryPi')),
            ],
        ),
        migrations.AddField(
            model_name='light',
            name='pi',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='smartpihome.RaspberryPi'),
        ),
        migrations.AddField(
            model_name='distancesensor',
            name='pi',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='smartpihome.RaspberryPi'),
        ),
    ]
