# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartpihome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distancesensor',
            name='pi',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='smartpihome.RaspberryPi'),
        ),
        migrations.AddField(
            model_name='light',
            name='pi',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='smartpihome.RaspberryPi'),
        ),
    ]
